package Boundary.GestioneMenu;

import Boundary.GestioneProfiloRistorante.FormGestioneProfilo;
import Controller.ControllerGestioneAttivita;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;

public class FormSelezioneRistorante {
    private JTable ristorantiTable;
    private JPanel contentPane;
    private JButton gestioneButton;
    private DefaultTableModel tableModel;

    private JFrame frame;
    private FormGestioneMenu classFormGestioneMenu;
    private JFrame formGestioneMenu;
    private FormGestioneProfilo classFormGestioneProfilo;
    private JFrame formGestioneProfilo;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    // Il parametro "modalita" determina quale schermata verrà aperta
    // dopo la selezione del ristorante.
    public JFrame apriFormSelezioneRistorante(String modalita){

        frame = new JFrame("Selezione Ristorante");

        frame.setContentPane(contentPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);

        // Definizione delle colonne visualizzate nella tabella dei ristoranti.
        String[] colonne = {"ID", "Nome", "Descrizione", "Indirizzo"};

        // Creo il modello della tabella. Tutte le celle sono in sola lettura
        // poiché l'utente deve soltanto selezionare un ristorante.
        tableModel = new DefaultTableModel(colonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Associa il modello alla tabella grafica.
        ristorantiTable.setModel(tableModel);

        // Richiede al controller la lista dei ristoranti appartenenti al ristoratore attualmente loggato.
        List<String[]> ristoranti = ControllerGestioneAttivita.ottieniRistoranti();

        // Popola la tabella aggiungendo una riga per ogni ristorante restituito dal controller.
        for (String[] ristorante : ristoranti) {
            tableModel.addRow(ristorante);
        }

        // Aggiunge la gestione dell'evento di click sul pulsante "Gestisci".
        gestioneButton.addActionListener(e -> {

            // Ottiene l'indice della riga selezionata dall'utente.
            int riga = ristorantiTable.getSelectedRow();

            // Se nessuna riga è stata selezionata, mostra un messaggio di errore
            // e interrompe l'operazione.
            if (riga == -1) {
                JOptionPane.showMessageDialog(frame, "Seleziona un ristorante.",
                        "Errore", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Recupera l'identificativo del ristorante selezionato.
            // L'id verrà utilizzato per caricare i dati corretti nella schermata successiva.
            Long idRistorante = Long.parseLong(
                    tableModel.getValueAt(riga, 0).toString()
            );

            // Se la modalità richiesta è "menu", apre la schermata di gestione del menu
            // relativa al ristorante selezionato.
            if ("menu".equals(modalita)) {
                apriGestioneMenu(idRistorante);
                //new FormGestioneMenu(idRistorante).setVisible(true);

            // Se la modalità richiesta è "profilo", apre la schermata di gestione del profilo ristorante.
            } else if ("profilo".equals(modalita)) {
                apriGestioneProfilo();
                //new FormGestioneProfilo().setVisible(true);
            }

            // Chiude la finestra corrente dopo l'apertura della schermata successiva.
            frame.dispose();
        });

        return frame;
    }

    private void apriGestioneMenu(Long idRistorante){

        if (formGestioneMenu == null || !formGestioneMenu.isDisplayable()) {

            classFormGestioneMenu = new FormGestioneMenu();
            formGestioneMenu = classFormGestioneMenu.apriFormGestioneMenu(idRistorante);

            // Serve a centrare la finestra sullo schermo.
            formGestioneMenu.setLocationRelativeTo(null);

            // Rende visibile la finestra a schermo.
            formGestioneMenu.setVisible(true);
        }else {
            formGestioneMenu.toFront();
            formGestioneMenu.requestFocus();
        }

        // Rendo invisibile la Home.
        frame.setVisible(false);

        formGestioneMenu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                //frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
                frame.setVisible(true);
            }
        });
    }

    private void apriGestioneProfilo(){

        if (formGestioneProfilo == null || !formGestioneProfilo.isDisplayable()) {

            classFormGestioneProfilo = new FormGestioneProfilo();
            formGestioneProfilo = classFormGestioneProfilo.apriFormGestioneProfilo();

            // Serve a centrare la finestra sullo schermo.
            formGestioneProfilo.setLocationRelativeTo(null);

            // Rende visibile la finestra a schermo.
            formGestioneProfilo.setVisible(true);
        }else {
            formGestioneProfilo.toFront();
            formGestioneProfilo.requestFocus();
        }

        // Rendo invisibile la Home.
        frame.setVisible(false);

        formGestioneProfilo.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                //frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
                frame.setVisible(true);
            }
        });
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ristorantiTable = new JTable();
        scrollPane1.setViewportView(ristorantiTable);
        gestioneButton = new JButton();
        gestioneButton.setText("Gestisci");
        contentPane.add(gestioneButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    /*public static void main(String[] args) {
        SwingUtilities.invokeLater(() ->
                new FormSelezioneRistorante("menu").setVisible(true));
    }*/

}
