package Boundary.GestioneMenu;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import Controller.ControllerGestioneAttivita;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class FormGestioneMenu {

    private JTable piattiTable;
    private JButton inserisciButton;
    private JButton modificaButton;
    private JButton rimuoviButton;
    private JLabel esitoLabel;
    private JPanel panel2;
    private JPanel contentPane;

    private JFrame frame;

    private DefaultTableModel tableModel;

    // Identificativo del ristorante di cui si sta gestendo il menù.
    private Long idRistorante;

    // Indica se è attualmente in corso la modifica di un piatto esistente.
    private boolean inModifica = false;

    // Indica se è attualmente in corso l'inserimento di un nuovo piatto.
    private boolean inInserimento = false;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /*Costruisce la schermata di gestione del menù di un ristorante.
      Riceve l'identificativo del ristorante e consente al ristoratore
      di inserire, modificare o rimuovere i piatti presenti nel menù. */
    public JFrame apriFormGestioneMenu(Long idRistorante) {

        frame = new JFrame("Gestione Menù");

        // Memorizza l'identificativo del ristorante selezionato.
        this.idRistorante = idRistorante;

        frame.setContentPane(contentPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);

        esitoLabel.setText(" ");

        // Definizione delle colonne visualizzate nella tabella dei piatti.
        String[] colonne = {"ID", "Nome", "Descrizione", "Prezzo"};
        tableModel = new DefaultTableModel(colonne, 0) {

            /* Stabilisce quando una cella può essere modificata:
             - durante un inserimento è modificabile soltanto l'ultima riga;
             - durante una modifica sono modificabili le celle della riga selezionata;
             - negli altri casi la tabella è in sola lettura. */
            @Override
            public boolean isCellEditable(int row, int column) {

                if(column == 0){
                    return false;
                }

                if(inInserimento){
                    return row == tableModel.getRowCount()-1;
                }
                return inModifica;
            }
        };

        List<String[]> righe = ControllerGestioneAttivita.ottieniPiatti(idRistorante);
        for(String[] riga : righe){
            tableModel.addRow(riga);
        }

        // Associa il modello dati alla JTable.
        piattiTable.setModel(tableModel);

        /* Gestisce il caso d'uso "Inserimento Piatto".
         Al primo click viene aggiunta una nuova riga vuota,
         al secondo click vengono validati e salvati i dati inseriti. */
        inserisciButton.addActionListener(e -> {

            // Non è possibile inserire un nuovo piatto mentre è in corso una modifica.
            if(inModifica){
                esitoLabel.setText("Completa prima la modifica in corso.");
                esitoLabel.setForeground(Color.RED);
                return;
            }

            if(!inInserimento){

                // Attiva la modalità di inserimento.
                inInserimento = true;

                // Aggiorna il testo del pulsante per indicare che il prossimo click
                // confermerà l'inserimento.
                inserisciButton.setText("Conferma inserimento");

                // Aggiunge un nuova riga vuota che verrà compilata dall'utente.
                tableModel.addRow(new Object[]{"", "", "", ""});

                int nuovaRiga = tableModel.getRowCount()-1;

                piattiTable.setModel(tableModel);

                // Seleziona automaticamente la nuova riga e posiziona il cursore sul campo "Nome".
                piattiTable.setRowSelectionInterval(nuovaRiga, nuovaRiga);
                piattiTable.editCellAt(nuovaRiga, 1);

                esitoLabel.setText("Inserisci i dati del nuovo piatto e premi Conferma.");
                esitoLabel.setForeground(Color.BLACK);

                // Recupera e salva i dati inseriti nella nuova riga.
            } else {

                // Se una cella è ancora in modifica, forza il salvataggio del valore inserito.
                if(piattiTable.isEditing()){
                    piattiTable.getCellEditor().stopCellEditing();
                }

                int riga = tableModel.getRowCount()-1;

                // Recupera i dati inseriti dall'utente nella nuova riga.
                String nome = tableModel.getValueAt(riga,1).toString();
                String descrizione = tableModel.getValueAt(riga,2).toString();
                String prezzo = tableModel.getValueAt(riga,3).toString();

                // Verifica che i campi obbligatori siano stati compilati.
                if(nome.isBlank() || prezzo.isBlank()){
                    esitoLabel.setText("Nome e prezzo sono obbligatori.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Controlla che il prezzo inserito sia un valore numerico valido.
                try{ Float.parseFloat(prezzo); }
                catch(NumberFormatException ex){
                    esitoLabel.setText("Il prezzo deve essere un numero valido.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Richiede al controller l'inserimento del nuovo piatto nel menù del ristorante.
                boolean esito = ControllerGestioneAttivita.inserisciPiattoMenu(
                        idRistorante,
                        nome,
                        descrizione,
                        Float.parseFloat(prezzo)
                );

                if (!esito) {
                    esitoLabel.setText("Errore durante l'inserimento.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Disattiva la modalità di inserimento e ripristina il testo originale del pulsante.
                inInserimento = false;
                inserisciButton.setText("Aggiungi piatto");
                piattiTable.setModel(tableModel);

                // Svuota la tabella corrente (serve per ricaricarla dopo).
                tableModel.setRowCount(0);

                // Recupera dal controller l'elenco aggiornato dei piatti presenti nel menù.
                List<String[]> piatti = ControllerGestioneAttivita.ottieniPiatti(idRistorante);

                /* Reinserisce tutti i piatti nella tabella. Questo passaggio permette di visualizzare
                   l'identificativo assegnato automaticamente dal database al nuovo piatto. */
                for (String[] piatto : piatti) {
                    tableModel.addRow(piatto);
                }

                // Mostra il messaggio di conferma dell'operazione.
                esitoLabel.setText("Piatto aggiunto con successo!");
                esitoLabel.setForeground(Color.GREEN);
            }
        });

        /* Aggiungo un'azione al click del pulsante "modificaButton".
            Il pulsante lavora in due modalità:
            - al primo click abilita la modifica della riga selezionata;
            - al secondo click salva le modifiche effettuate. */
        modificaButton.addActionListener(e -> {

            // Non è permessa la modifica di un piatto esistente
            // mentre è in corso l'inserimento di un nuovo piatto.
            if(inInserimento){
                esitoLabel.setText("Completa prima l'inserimento in corso.");
                esitoLabel.setForeground(Color.RED);
                return;
            }

            if (!inModifica) {
                int riga = piattiTable.getSelectedRow();

                // Verifica che l'utente abbia selezionato un piatto da modificare.
                if (riga == -1) {
                    esitoLabel.setText("Seleziona un piatto da modificare.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Attiva la modalità di modifica.
                inModifica = true;

                // Aggiorna il testo del pulsante per indicare che il prossimo click confermerà le modifiche.
                modificaButton.setText("Conferma modifiche");

                esitoLabel.setText("Modifica i dati del piatto e premi Conferma.");
                esitoLabel.setForeground(Color.BLACK);

                piattiTable.setModel(tableModel);
                piattiTable.setRowSelectionInterval(riga, riga);

            } else {

                // Se l'utente sta ancora modificando una cella, salva il valore prima di proseguire.
                if (piattiTable.isEditing()) {
                    piattiTable.getCellEditor().stopCellEditing();
                }

                int riga = piattiTable.getSelectedRow();

                if (riga == -1) {
                    esitoLabel.setText("Seleziona il piatto modificato.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Recupera l'identificativo del piatto selezionato. L'id viene utilizzato
                // per individuare correttamente il record da aggiornare nel database.
                Long idPiatto = Long.parseLong(
                        tableModel.getValueAt(riga, 0).toString()
                );

                // Recupera i nuovi valori inseriti dall'utente.
                String nome = tableModel.getValueAt(riga, 1).toString();
                String descrizione = tableModel.getValueAt(riga, 2).toString();
                String prezzo = tableModel.getValueAt(riga, 3).toString();

                // Verifica che i campi obbligatori siano stati compilati.
                if (nome.isBlank() || prezzo.isBlank()) {
                    esitoLabel.setText("Nome e prezzo sono obbligatori.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Controlla che il prezzo inserito sia un numero valido.
                try {
                    Float.parseFloat(prezzo);
                } catch (NumberFormatException ex) {
                    esitoLabel.setText("Il prezzo deve essere un numero valido.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Richiede al controller l'aggiornamento dei dati del piatto.
                boolean esito = ControllerGestioneAttivita.modificaPiattoMenu(
                                idRistorante,
                                idPiatto,
                                nome,
                                descrizione,
                                Float.parseFloat(prezzo)
                        );

                if (!esito) {
                    esitoLabel.setText("Errore durante la modifica.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Disattiva la modalità di modifica e ripristina il comportamento normale della tabella.
                inModifica = false;

                // Ripristina il testo originale del pulsante.
                modificaButton.setText("Modifica piatto");

                piattiTable.setModel(tableModel);

                esitoLabel.setText("Piatto modificato con successo!");
                esitoLabel.setForeground(Color.GREEN);
            }
        });

        // Gestisce il caso d'uso "Eliminazione Piatto". Consente di eliminare il piatto selezionato
        // dopo una conferma esplicita da parte dell'utente.
        rimuoviButton.addActionListener(e -> {

            // Non è possibile eliminare un piatto durante una modifica o un inserimento.
            if (inModifica || inInserimento) {
                esitoLabel.setText("Completa prima la modifica in corso.");
                esitoLabel.setForeground(Color.RED);
                return;
            }

            // Se una cella è ancora in modifica, salva il valore prima di procedere.
            if (piattiTable.isEditing()) {
                piattiTable.getCellEditor().stopCellEditing();
            }

            int riga = piattiTable.getSelectedRow();

            // Verifica che sia stato selezionato un piatto.
            if (riga == -1) {
                esitoLabel.setText("Seleziona un piatto da rimuovere.");
                esitoLabel.setForeground(Color.RED);
                return;
            }

            // Recupera il nome del piatto da mostrare nel messaggio di conferma.
            String nome = (String) tableModel.getValueAt(riga, 1);

            // Mostra una finestra di conferma prima dell'eliminazione definitiva.
            int conferma = JOptionPane.showConfirmDialog(
                    frame,
                    "Vuoi davvero eliminare il piatto \"" + nome + "\"?",
                    "Conferma eliminazione",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            // Se l'utente annulla l'operazione, interrompe l'esecuzione.
            if (conferma != JOptionPane.YES_OPTION) {
                return;
            }

            // Recupera l'identificativo del piatto da eliminare.
            Long idPiatto = Long.parseLong(tableModel.getValueAt(riga, 0).toString());

            // Richiede al controller la rimozione del piatto dal menù.
            boolean esito = ControllerGestioneAttivita.eliminaPiattoMenu(idRistorante, idPiatto);

            // Se l'operazione va a buon fine, rimuove la riga della tabella.
            if (esito) {
                tableModel.removeRow(riga);
                esitoLabel.setText("Piatto rimosso con successo!");
                esitoLabel.setForeground(Color.GREEN);
            } else {
                esitoLabel.setText("Errore durante la rimozione.");
                esitoLabel.setForeground(Color.RED);
            }
        });

        return frame;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        piattiTable = new JTable();
        scrollPane1.setViewportView(piattiTable);
        panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        inserisciButton = new JButton();
        inserisciButton.setText("Aggiungi piatto");
        panel2.add(inserisciButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        modificaButton = new JButton();
        modificaButton.setText("Modifica piatto");
        panel2.add(modificaButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rimuoviButton = new JButton();
        rimuoviButton.setText("Rimuovi piatto");
        panel2.add(rimuoviButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        esitoLabel = new JLabel();
        esitoLabel.setText("");
        contentPane.add(esitoLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    /*public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new FormGestioneMenu(1L).setVisible(true));
    }*/
}
