package Boundary;

import Boundary.GestioneMenu.FormSelezioneRistorante;
import Boundary.GestioneProfiloRistorante.FormGestioneProfilo;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FormPannelloRistoratore {
    private JPanel contentPane;
    private JButton gestioneMenuButton;
    private JButton gestioneProfiloButton;

    private JFrame frame;

    private FormSelezioneRistorante classFormSelezioneRistorante;
    private JFrame formSelezioneRistorante;
    private FormGestioneProfilo classFormGestioneProfilo;
    private JFrame formGestioneProfilo;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public JFrame apriFormPannelloRistoratore() {

        frame = new JFrame("Pannello Ristoratore");

        frame.setContentPane(contentPane);
        frame.setTitle("Pannello Ristoratore");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        contentPane.setBorder(
                BorderFactory.createEmptyBorder(20,20,20,20)
        );

        for(Component c : contentPane.getComponents()) {
            c.setFont(new Font(
                    c.getFont().getName(),
                    Font.PLAIN,
                    14
            ));
        }

        frame.pack();
        frame.setLocationRelativeTo(null);

        // Aggiungo un'azione al click del pulsante "Gestisci Menu".
        gestioneMenuButton.addActionListener(e -> {

            // Apre la schermata di selezione del ristorante per la gestione del menù.
            //new FormSelezioneRistorante("menu").setVisible(true);
            apriFormSelezioneRistorante("menu");

            // Chiude il pannello corrente.
            //frame.dispose();
        });

        // Aggiungo un'azione al click del pulsante "Gestisci Profilo Ristorante".
        gestioneProfiloButton.addActionListener(e -> {

            apriFormGestioneProfilo();

            // Apre la schermata di gestione del profilo del ristorante.
            //new FormGestioneProfilo().setVisible(true);

            // Chiude il pannello corrente.
            //frame.dispose();
        });

        return frame;
    }

    private void apriFormSelezioneRistorante(String modalita){

        if (formSelezioneRistorante == null || !formSelezioneRistorante.isDisplayable()) {

            classFormSelezioneRistorante = new FormSelezioneRistorante();
            formSelezioneRistorante = classFormSelezioneRistorante.apriFormSelezioneRistorante(modalita);

            // Serve a centrare la finestra sullo schermo.
            formSelezioneRistorante.setLocationRelativeTo(null);

            // Rende visibile la finestra a schermo.
            formSelezioneRistorante.setVisible(true);
        }else {
            formSelezioneRistorante.toFront();
            formSelezioneRistorante.requestFocus();
        }

        // Rendo invisibile la Home.
        frame.setVisible(false);

        formSelezioneRistorante.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                //frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
                frame.setVisible(true);
            }
        });
    }

    private void apriFormGestioneProfilo(){

        if (formGestioneProfilo == null || !formGestioneProfilo.isDisplayable()) {

            classFormGestioneProfilo = new FormGestioneProfilo();
            formGestioneProfilo = classFormGestioneProfilo.apriFormGestioneProfilo();

            // Serve a centrare la finestra sullo schermo.
            formGestioneProfilo.setLocationRelativeTo(null);

            // Rende visibile la finestra a schermo.
            formGestioneProfilo.setVisible(true);
        }else {
            formGestioneProfilo.toFront();
            formGestioneProfilo.requestFocus();
        }

        // Rendo invisibile la Home.
        frame.setVisible(false);

        formGestioneProfilo.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                //frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
                frame.setVisible(true);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        gestioneMenuButton = new JButton();
        gestioneMenuButton.setText("Gestisci Menù");
        contentPane.add(gestioneMenuButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gestioneProfiloButton = new JButton();
        gestioneProfiloButton.setText("Gestisci Profilo Ristorante");
        contentPane.add(gestioneProfiloButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }



    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    /*public static void main(String[] args) {
        SwingUtilities.invokeLater(() ->
                new FormPannelloRistoratore().setVisible(true));
    }*/
}
