package Boundary.GestioneProfiloRistorante;

import Controller.ControllerGestioneAttivita;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class FormGestioneProfilo {
    private JTable ristorantiTable;
    private JButton aggiungiButton;
    private JButton modificaButton;
    private JButton rimuoviButton;
    private JPanel contentPane;
    private JLabel esitoLabel;

    private DefaultTableModel tableModel;

    private JFrame frame;


    // Indica se stiamo in modalità modifica o no.
    private boolean inModifica = false;

    private String[] colonne = {"ID", "Nome", "Descrizione", "Indirizzo"};

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public JFrame apriFormGestioneProfilo() {

        frame = new JFrame("Gestione Profilo Ristorante");

        frame.setContentPane(contentPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);

        esitoLabel.setText(" ");

        /* Modello della tabella dei ristoranti.
           La colonna dell'ID non sarà mai modificabile,
           mentre le altre colonne potranno essere modificate solo quando è attiva la modalità modifica. */
        tableModel = new DefaultTableModel(colonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return inModifica && column !=0; //colonna ID non modificabile
            }
        };

        ristorantiTable.setModel(tableModel);

        // Ottengo dal controller la lista di tutti i ristoranti associati al ristoratore attualmente loggato.
        List<String[]> ristoranti = ControllerGestioneAttivita.ottieniRistoranti();

        // Popolo la tabella aggiungendo una riga per ogni ristorante restituito.
        for (String[] ristorante : ristoranti) {
            tableModel.addRow(ristorante);
        }

        // Aggiungo un'azione al click del pulsante "aggiungiButton".
        aggiungiButton.addActionListener(e -> {

            //Non è possibile aggiungere un ristorante
            // mentre è in corso la modifica di uno esistente.
            if(inModifica){

                // Mostra messaggio di errore.
                esitoLabel.setText("Completa prima la modifica in corso.");
                esitoLabel.setForeground(Color.RED);
                return;
            }

            /* Apre la finestra di inserimento di un nuovo ristorante.
                Viene passato il riferimento al form corrente per consentire
                l'aggiornamento automatico della tabella dopo il salvataggio. */
            new FormAggiungiRistorante(this).setVisible(true);
        });

        /* Aggiungo un'azione al click del pulsante "modificaButton".
            Il pulsante lavora in due modalità:
            - al primo click abilita la modifica della riga selezionata;
            - al secondo click salva le modifiche effettuate. */
        modificaButton.addActionListener(e -> {

            // Se non è già attiva la modalità modifica:
            if (!inModifica) {

                // Ottengo la riga selezionata dall'utente.
                int riga = ristorantiTable.getSelectedRow();

                // Se nessuna riga è stata selezionata:
                if (riga == -1) {

                    // Mostra messaggio di errore.
                    esitoLabel.setText("Seleziona un ristorante da modificare.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Attiva la modalità modifica.
                inModifica = true;

                // Aggiorna il testo del pulsante.
                modificaButton.setText("Conferma modifiche");

                // Mostra messaggio informativo.
                esitoLabel.setText("Modifica i campi desiderati, poi clicca Conferma.");
                esitoLabel.setForeground(Color.BLACK);

                // Aggiorna la tabella rendendo modificabili le celle consentite.
                ristorantiTable.setModel(tableModel);

                // Mantiene selezionata la riga scelta dall'utente.
                ristorantiTable.setRowSelectionInterval(riga, riga);

            } else {

                // Se l'utente sta ancora modificando una cella,
                // termina la modifica prima di procedere al salvataggio.
                if (ristorantiTable.isEditing()) {
                    ristorantiTable.getCellEditor().stopCellEditing();
                }

                int rigaSelezionata = ristorantiTable.getSelectedRow();
                if (rigaSelezionata == -1) {
                    esitoLabel.setText("Seleziona la riga modificata.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Recupera l'id del ristorante selezionato.
                // Sarà utilizzato dal controller per individuare il record da aggiornare.
                Long idRistorante = Long.parseLong(
                        tableModel.getValueAt(rigaSelezionata, 0).toString()
                );

                // Recupero i nuovi valori presenti nella tabella.
                String nome = (String) tableModel.getValueAt(rigaSelezionata, 1);
                String descrizione = (String) tableModel.getValueAt(rigaSelezionata, 2);
                String indirizzo = (String) tableModel.getValueAt(rigaSelezionata, 3);

                // Verifico che i campi obbligatori siano stati compilati.
                if (nome == null || nome.isBlank() || indirizzo == null || indirizzo.isBlank()) {

                    // Mostra messaggio di errore.
                    esitoLabel.setText("Nome e indirizzo sono obbligatori.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Richiedo al controller l'aggiornamento dei dati del ristorante.
                boolean esito =
                        ControllerGestioneAttivita.aggiornaProfiloRistorante(
                                idRistorante,
                                nome,
                                descrizione,
                                indirizzo
                        );

                if (!esito) {
                    esitoLabel.setText("Errore durante la modifica.");
                    esitoLabel.setForeground(Color.RED);
                    return;
                }

                // Disattiva la modalità modifica.
                inModifica = false;

                // Ripristina il testo originale del pulsante.
                modificaButton.setText("Modifica Ristorante");

                // Aggiorna la tabella rendendo nuovamente le celle non modificabili.
                ristorantiTable.setModel(tableModel);

                // Mostra messaggio di conferma.
                esitoLabel.setText("Ristorante modificato con successo!");
                esitoLabel.setForeground(Color.GREEN);
            }
        });

        // Aggiungo un'azione al click del pulsante "rimuoviButton".
        rimuoviButton.addActionListener(e -> {

            // Non è possibile eliminare un ristorante mentre è in corso una modifica.
            if (inModifica) {

                // Mostra messaggio di errore.
                esitoLabel.setText("Completa prima la modifica in corso.");
                esitoLabel.setForeground(Color.RED);
                return;
            }

            // Ottengo la riga selezionata dall'utente.
            int riga = ristorantiTable.getSelectedRow();
            if (riga == -1) {
                esitoLabel.setText("Seleziona un ristorante da rimuovere.");
                esitoLabel.setForeground(Color.RED);
                return;
            }

            // Recupera il nome del ristorante selezionato.
            // Verrà mostrato nella finestra di conferma.
            String nome = (String) tableModel.getValueAt(riga, 1);

            // Mostra una finestra di conferma prima dell'eliminazione.
            int conferma = JOptionPane.showConfirmDialog(
                    frame,
                    "Vuoi davvero eliminare il ristorante \"" + nome + "\"?",
                    "Conferma eliminazione",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            // Se l'utente non conferma l'operazione, l'eliminazione viene annullata.
            if (conferma != JOptionPane.YES_OPTION) { return; }

            // Recupero l'identificativo del ristorante da eliminare.
            Long idRistorante = Long.parseLong(tableModel.getValueAt(riga, 0).toString());

            // Richiedo al controller la rimozione del ristorante.
            boolean esito = ControllerGestioneAttivita.rimuoviRistorante(idRistorante);

            if (esito) {
                tableModel.removeRow(riga);
                esitoLabel.setText("Ristorante rimosso con successo!");
                esitoLabel.setForeground(Color.GREEN);
            } else {
                esitoLabel.setText("Errore durante la rimozione.");
                esitoLabel.setForeground(Color.RED);
            }
        });

        return frame;
    }

    /* Metodo richiamato da FormAggiungiRistorante dopo la creazione
    di un nuovo ristorante. Aggiunge una nuova riga alla tabella
    e mostra un messaggio di conferma all'utente. */
    public void aggiungiRigaRistorante(String id, String nome,
                                       String descrizione, String indirizzo) {
        tableModel.addRow(new Object[]{id, nome, descrizione, indirizzo});
        esitoLabel.setText("Ristorante aggiunto con successo!");
        esitoLabel.setForeground(Color.GREEN);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ristorantiTable = new JTable();
        scrollPane1.setViewportView(ristorantiTable);
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        aggiungiButton = new JButton();
        aggiungiButton.setText("Aggiungi Ristorante");
        contentPane.add(aggiungiButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modificaButton = new JButton();
        modificaButton.setText("Modifica Ristorante");
        contentPane.add(modificaButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rimuoviButton = new JButton();
        rimuoviButton.setText("Rimuovi Ristorante");
        contentPane.add(rimuoviButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        esitoLabel = new JLabel();
        esitoLabel.setText("");
        contentPane.add(esitoLabel, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    /*public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new FormGestioneProfilo().setVisible(true));
    }*/
}
