package Boundary.Monitoraggio;

import Controller.ControllerMonitoraggio;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.Locale;

public class FormMonitoraggio {

    // --- Componenti presenti nella finestra ---
    private JPanel monitoraggioPanel;
    private JTextField txtDataInizio;
    private JTextField txtDataFine;
    private JButton btnCercaOrdini;
    private JLabel lblRisultatoOrdini;
    private JTable tabellaRistoranti;
    private JScrollPane scrollPaneRistoranti; // Fondamentale per vedere i nomi delle colonne
    private JButton btnAggiornaRistoranti;
    private JLabel lblVolumeMedio;
    private JButton btnCalcolaVolume;

    // Riferimento al frame principale
    private JFrame frame;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Crea e mostra il JFrame per il monitoraggio.
     * Allineato graficamente a FrameRistorantiAperti.
     */
    public JFrame apriFormMonitoraggio() {

        frame = new JFrame("Monitoraggio Attività Piattaforma");
        frame.setContentPane(monitoraggioPanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // --- Inizializzazione della Tabella (con le colonne visibili) ---
        String[] colonne = {"ID", "Nome Ristorante", "Numero Ordini"};
        DefaultTableModel model = new DefaultTableModel(colonne, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Impedisce la modifica manuale delle celle
            }
        };
        tabellaRistoranti.setModel(model);

        // --- Azione: Cerca ordini in un intervallo di tempo ---
        btnCercaOrdini.addActionListener(e -> {
            String dataInizio = txtDataInizio.getText().trim();
            String dataFine = txtDataFine.getText().trim();

            // 1. Controllo campi vuoti (Soddisfa il TC4)
            if (dataInizio.isEmpty() || dataFine.isEmpty()) {
                JOptionPane.showMessageDialog(
                        frame,
                        "Inserisci entrambe le date nel formato YYYY-MM-DD.",
                        "Campi mancanti",
                        JOptionPane.WARNING_MESSAGE
                );
                return; // Blocca l'esecuzione qui
            }

            // 2. Controllo formato Regex (Soddisfa il TC5)
            if (!dataInizio.matches("\\d{4}-\\d{2}-\\d{2}") || !dataFine.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(
                        frame,
                        "Formato data non valido.\nInserisci rigorosamente il formato YYYY-MM-DD (es. 2026-06-13).",
                        "Errore Formato",
                        JOptionPane.ERROR_MESSAGE
                );
                return; // Blocca l'esecuzione qui
            }

            // 3. Delega al Controller
            long totale = ControllerMonitoraggio.visualizzaOrdiniTotali(java.time.LocalDate.parse(dataInizio), java.time.LocalDate.parse(dataFine));

            if (totale == -1) {
                JOptionPane.showMessageDialog(frame, "Errore durante la ricerca. Verifica che le date siano logicamente corrette (inizio <= fine).", "Errore", JOptionPane.ERROR_MESSAGE);
                lblRisultatoOrdini.setText("—");
            } else {
                lblRisultatoOrdini.setText(String.valueOf(totale));
            }
        });

        // --- Azione: Aggiorna tabella ristoranti più attivi ---
        btnAggiornaRistoranti.addActionListener(e -> {
            List<String[]> righe = ControllerMonitoraggio.visualizzaRistorantiPiuAttivi();
            model.setRowCount(0); // Svuota la tabella prima di ricaricare i dati
            for (String[] riga : righe) {
                model.addRow(riga);
            }
        });

        // --- Azione: Calcola volume medio ---
        btnCalcolaVolume.addActionListener(e -> {
            String media = ControllerMonitoraggio.visualizzaVolumeMedioOrdini();
            lblVolumeMedio.setText(media + " piatti per ordine");
        });

        // --- Applicazione dello Stile Grafico (Padding, Font, Dimensioni) ---
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(frame);
        } catch (Exception ignored) {}

        // Margini esterni del pannello
        monitoraggioPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Proprietà della tabella
        tabellaRistoranti.setFillsViewportHeight(true);
        tabellaRistoranti.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabellaRistoranti.setRowHeight(32);

        // Regolazione dimensioni colonne (L'ID è piccolo, il Nome è grande)
        tabellaRistoranti.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabellaRistoranti.getColumnModel().getColumn(0).setMaxWidth(80);

        // Uniformazione dei font per tutti i componenti
        for (Component c : monitoraggioPanel.getComponents()) {
            if (c.getFont() != null) {
                c.setFont(new Font(c.getFont().getName(), Font.PLAIN, 16));
            }
            if (c instanceof JScrollPane) {
                ((JScrollPane) c).getViewport().getView().setFont(new Font("Dialog", Font.PLAIN, 15));
            }
        }

        frame.setSize(800, 600);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        return frame;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        monitoraggioPanel = new JPanel();
        monitoraggioPanel.setLayout(new GridLayoutManager(6, 4, new Insets(0, 0, 0, 0), -1, -1));

        // Aggiunta dello JScrollPane per abilitare le intestazioni della tabella
        scrollPaneRistoranti = new JScrollPane();
        monitoraggioPanel.add(scrollPaneRistoranti, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 150), null, 0, false));
        tabellaRistoranti = new JTable();
        scrollPaneRistoranti.setViewportView(tabellaRistoranti);

        final Spacer spacer1 = new Spacer();
        monitoraggioPanel.add(spacer1, new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lblVolumeMedio = new JLabel();
        lblVolumeMedio.setText("Volume Medio");
        monitoraggioPanel.add(lblVolumeMedio, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCalcolaVolume = new JButton();
        btnCalcolaVolume.setText("Calcola Volume");
        monitoraggioPanel.add(btnCalcolaVolume, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAggiornaRistoranti = new JButton();
        btnAggiornaRistoranti.setText("Aggiorna Ristoranti");
        monitoraggioPanel.add(btnAggiornaRistoranti, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCercaOrdini = new JButton();
        btnCercaOrdini.setText("Cerca Ordini");
        monitoraggioPanel.add(btnCercaOrdini, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblRisultatoOrdini = new JLabel();
        lblRisultatoOrdini.setText("Risultato Ordini");
        monitoraggioPanel.add(lblRisultatoOrdini, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        monitoraggioPanel.add(spacer2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        txtDataInizio = new JTextField();
        txtDataInizio.setText("Data Inizio");
        monitoraggioPanel.add(txtDataInizio, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtDataFine = new JTextField();
        txtDataFine.setText("Data Fine");
        monitoraggioPanel.add(txtDataFine, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return monitoraggioPanel;
    }
}