package Boundary;

import Boundary.EffettuaOrdine.FrameMenu;
import Boundary.Login.FormLogin;
import Boundary.Registrazione.FormRegistrazione;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FormHome {
    private JButton loginButton;
    private JButton registratiButton;
    private JLabel titoloLabel;
    private JPanel contentPane;

    private JFrame frame;

    private FormLogin classFormLogin;
    private JFrame formLogin;
    private FormRegistrazione classFormRegistrazione;
    private JFrame formRegistrazione;

    public JFrame apriFormHome() {

        frame = new JFrame("Food Delivery");

        frame.setContentPane(contentPane);
        frame.setSize(500,300);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);

        // Aggiungo un'azione al click del pulsante "loginButton".
        loginButton.addActionListener(e -> {
            apriLogin();
        });

        // Aggiungo un'azione al click del pulsante "registratiButton".
        registratiButton.addActionListener(e -> {
            apriRegistrazione();
        });

        // Stile grafico.
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName()
            );
            SwingUtilities.updateComponentTreeUI(frame);
        } catch (Exception ignored) {}

        contentPane.setBorder(
                BorderFactory.createEmptyBorder(20,20,20,20)
        );

        for(Component c : contentPane.getComponents()) {
            c.setFont(new Font(
                    c.getFont().getName(),
                    Font.PLAIN,
                    16
            ));
        }

        return frame;
    }

    private void apriLogin(){
        // Apro la schermata di login.
        if (formLogin == null || !formLogin.isDisplayable()) {

            classFormLogin = new FormLogin();
            formLogin = classFormLogin.apriFormLogin();

            // Serve a centrare la finestra sullo schermo.
            formLogin.setLocationRelativeTo(null);

            // Rende visibile la finestra a schermo.
            formLogin.setVisible(true);
        }else {
            formLogin.toFront();
            formLogin.requestFocus();
        }

        // Chiudo la schermata Home.
        //dispose();

        // Rendo invisibile la Home.
        frame.setVisible(false);

        formLogin.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                if(classFormLogin.avviaRegistrazione){
                    apriRegistrazione();
                }
                else{
                    frame.setVisible(true);
                }

            }
        });
    }

    private void apriRegistrazione(){
        if (formRegistrazione == null || !formRegistrazione.isDisplayable()) {

            classFormRegistrazione = new FormRegistrazione();
            formRegistrazione = classFormRegistrazione.apriFormRegistrazione();

            formRegistrazione.setLocationRelativeTo(null);

            formRegistrazione.setVisible(true);
        }else {
            formRegistrazione.toFront();
            formRegistrazione.requestFocus();
        }

        //dispose();

        // Rendo invisibile la Home.
        frame.setVisible(false);

        formRegistrazione.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {

                if (classFormRegistrazione.registrazioneAvvenuta) {
                    apriLogin();
                }
                else {
                    frame.setVisible(true);
                }
            }

        });
    }

    /*public static void main(String[] args) {

        SwingUtilities.invokeLater(() ->
                new FormHome().apriFormHome().setVisible(true)
        );
    }*/

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        titoloLabel = new JLabel();
        titoloLabel.setText("Food Delivery");
        contentPane.add(titoloLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Effettua login");
        contentPane.add(loginButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        registratiButton = new JButton();
        registratiButton.setText("Registrati");
        contentPane.add(registratiButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}


