package Boundary.EffettuaOrdine;

import Controller.ControllerEffettuaOrdine;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.Locale;

public class FrameRistorantiAperti {

    // Elementi presenti nella finestra.
    private JPanel scegliRistorantePanel;
    private JTable tableRistorantiAperti;
    private JScrollPane scrollPanelRistorantiAperti;
    private JLabel mainLabel;
    private JButton selezionaRistoranteButton;

    /* Ho un riferimento alla finestra successiva, ovvero FrameMenu. Questo mi servirà per poter verificare
       che non sia già attiva una finestra FrameMenu se l'utente dovesse cliccare "Seleziona ristorante" più volte. */
    private JFrame frameMenu;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        scegliRistorantePanel = new JPanel();
        scegliRistorantePanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        scegliRistorantePanel.setPreferredSize(new Dimension(600, 400));
        scrollPanelRistorantiAperti = new JScrollPane();
        Font scrollPanelRistorantiApertiFont = this.$$$getFont$$$(null, -1, -1, scrollPanelRistorantiAperti.getFont());
        if (scrollPanelRistorantiApertiFont != null)
            scrollPanelRistorantiAperti.setFont(scrollPanelRistorantiApertiFont);
        scegliRistorantePanel.add(scrollPanelRistorantiAperti, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tableRistorantiAperti = new JTable();
        tableRistorantiAperti.setAutoCreateRowSorter(false);
        Font tableRistorantiApertiFont = this.$$$getFont$$$(null, -1, -1, tableRistorantiAperti.getFont());
        if (tableRistorantiApertiFont != null) tableRistorantiAperti.setFont(tableRistorantiApertiFont);
        tableRistorantiAperti.setIntercellSpacing(new Dimension(1, 1));
        tableRistorantiAperti.setPreferredScrollableViewportSize(new Dimension(400, 300));
        tableRistorantiAperti.setPreferredSize(new Dimension(500, 300));
        tableRistorantiAperti.setRowHeight(28);
        tableRistorantiAperti.setRowMargin(1);
        scrollPanelRistorantiAperti.setViewportView(tableRistorantiAperti);
        mainLabel = new JLabel();
        mainLabel.setText("Seleziona un ristorante");
        scegliRistorantePanel.add(mainLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        selezionaRistoranteButton = new JButton();
        selezionaRistoranteButton.setText("Seleziona");
        scegliRistorantePanel.add(selezionaRistoranteButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return scegliRistorantePanel;
    }

    // Metodo necessario per aprire la finestra di "Ristoranti aperti" da altre classi.
    // Restituisce il frame, cioè la finestra di "Ristoranti aperti".
    public JFrame apriFrameRistorantiAperti() {

        // Creo l'istanza del frame di Ristoranti Aperti con titolo "Effettua ordine".
        JFrame frame = new JFrame("Effettua ordine");

        // Imposta "confermaOrdinePanel" come attuale pannello visibile della finestra.
        frame.setContentPane(scegliRistorantePanel);

        // Specifica che al click della "X" della finestra, viene chiusa tutta l'applicazione.
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Ottengo dal controller una lista di stringhe dei ristoranti da visualizzare.
        List<String[]> righe = ControllerEffettuaOrdine.ricercaRistorantiAperti();

        // Le colonne che saranno visualizzate nella tabella dei ristoranti aperti.
        String[] colonne = {"ID", "Nome", "Descrizione", "Indirizzo"};

        // Creo il modello della tabella.
        DefaultTableModel model = new DefaultTableModel(colonne, 0) {

            // Override del metodo isCellEditable, per impedire che l'utente possa modificare le righe della tabella.
            @Override
            public boolean isCellEditable(int row, int column) {
                // Restituendo false, nessuna cella della tabella sarà modificabile dall'utente.
                return false;
            }
        };

        // Aggiunge al modello di tabella le stringhe dei ristoranti prelevate precedentemente dal controller.
        for (String[] riga : righe) {
            model.addRow(riga);
        }

        // Imposto il modello alla effettiva tabella visualizzata dei ristoranti.
        tableRistorantiAperti.setModel(model);

        // Aggiungo una azione al click del pulsante "selezionaRistoranteButton".
        selezionaRistoranteButton.addActionListener(e -> {

            // Ottengo l'indice della riga che l'utente ha selezionato con il mouse.
            int riga = tableRistorantiAperti.getSelectedRow();

            // Se l'utente non ha cliccato su nessuna riga:
            if (riga == -1) {
                // Mostra messaggio di errore "Seleziona un ristorante".
                JOptionPane.showMessageDialog(frame, "Seleziona un ristorante.",
                        "Errore", JOptionPane.ERROR_MESSAGE);
            }
            // Se l'utente ha invece selezionato una riga:
            else {
                // Ottengo l'id del ristorante selezionato, che si trova alla colonna 0 della riga selezionata.
                // Questo idRistorante dovrà essere passato per parametro alla nuova finestra "FrameMenu".
                Long idRistorante = Long.parseLong(tableRistorantiAperti.getValueAt(riga, 0).toString());

                // Se non è già attiva una finestra FrameMenu:
                if (frameMenu == null || !frameMenu.isDisplayable()) {

                    // Genero una nuova finestra FrameMenu, e la apro.
                    frameMenu = new FrameMenu().apriFrameMenu(idRistorante);

                    // Serve a centrare la finestra sullo schermo.
                    frameMenu.setLocationRelativeTo(null);

                    // Rende visibile la finestra a schermo.
                    frameMenu.setVisible(true);
                }
                // Se è già attiva una finestra FrameMenu:
                else {

                    // La finestra FrameMenu viene portata avanti sullo schermo.
                    frameMenu.toFront();
                    frameMenu.requestFocus();
                }

                // Una volta aperta la finestra del menù, rendo invisibile questa finestra di selezione ristoranti.
                frame.setVisible(false);

                // Aggiungo un'azione quando la finestra del menù viene chiusa.
                frameMenu.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent windowEvent) {
                        // Quando la finestra di menù si chiude, faccio riapparire quella di selezione ristoranti.
                        frame.setVisible(true);
                    }
                });
            }
        });

        // Altre proprietà grafiche della finestra.
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(frame);
        } catch (Exception ignored) {
        }
        scegliRistorantePanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        tableRistorantiAperti.setFillsViewportHeight(true);
        tableRistorantiAperti.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableRistorantiAperti.getColumnModel().getColumn(0).setPreferredWidth(40);
        tableRistorantiAperti.getColumnModel().getColumn(0).setMaxWidth(60);
        tableRistorantiAperti.setRowHeight(32);
        for (Component c : scegliRistorantePanel.getComponents()) {
            c.setFont(new Font(c.getFont().getName(), Font.PLAIN, 16));
            if (c instanceof JScrollPane) {
                ((JScrollPane) c).getViewport().getView().setFont(new Font(c.getFont().getName(), Font.PLAIN, 15));
            }
        }
        mainLabel.setFont(new Font(mainLabel.getFont().getName(), Font.BOLD, 20));

        frame.setSize(1100, 700);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        return frame;
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
