package Boundary.EffettuaOrdine;

import Controller.ControllerEffettuaOrdine;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;

public class FrameMenu {

    // Elementi presenti nella finestra.
    private JPanel aggiungiPiattiPanel;
    private JScrollPane scrollPanePiatti;
    private JTable tablePiatti;
    private JLabel labelMenu;
    private JButton aggiungiAlCarrelloButton;
    private JButton inviaOrdineButton;
    private JList<String> carrelloList;
    private JLabel carrelloLabel;

    /* Ho un riferimento alla finestra successiva, ovvero FrameConfermaOrdine. Questo mi servirà per poter verificare
       che non sia già attiva una finestra FrameConfermaOrdine se l'utente dovesse cliccare "Invia Ordine" più volte. */
    private FrameConfermaOrdine classConfermaOrdine;
    private JFrame frameConfermaOrdine;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        aggiungiPiattiPanel = new JPanel();
        aggiungiPiattiPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        scrollPanePiatti = new JScrollPane();
        aggiungiPiattiPanel.add(scrollPanePiatti, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tablePiatti = new JTable();
        scrollPanePiatti.setViewportView(tablePiatti);
        labelMenu = new JLabel();
        labelMenu.setText("Aggiungi i piatti al carrello");
        aggiungiPiattiPanel.add(labelMenu, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        aggiungiAlCarrelloButton = new JButton();
        aggiungiAlCarrelloButton.setText("Aggiungi al carrello");
        aggiungiPiattiPanel.add(aggiungiAlCarrelloButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inviaOrdineButton = new JButton();
        inviaOrdineButton.setText("Invia ordine");
        aggiungiPiattiPanel.add(inviaOrdineButton, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        carrelloList = new JList();
        aggiungiPiattiPanel.add(carrelloList, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        carrelloLabel = new JLabel();
        carrelloLabel.setText("Carrello");
        aggiungiPiattiPanel.add(carrelloLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return aggiungiPiattiPanel;
    }

    // Metodo necessario per aprire la finestra di menù da altre classi.
    // Restituisce il frame, cioè la finestra di menù.
    public JFrame apriFrameMenu(Long idRistorante) {

        // Creo l'istanza del frame di Menu con titolo "Effettua ordine".
        JFrame frame = new JFrame("Effettua ordine");

        // Imposta "aggiungiPiattiPanel" come attuale pannello visibile della finestra.
        frame.setContentPane(aggiungiPiattiPanel);

        // Specifica che al click della "X" della finestra, non viene chiusa tutta l'applicazione.
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Ottengo dal controller una lista dei piatti da visualizzare.
        List<String[]> righe = ControllerEffettuaOrdine.consultaMenuRistorante(idRistorante);

        // Le colonne che saranno visualizzate nella tabella dei ristoranti aperti.
        String[] colonne = {"ID", "Nome", "Descrizione", "Prezzo"};

        // Creo il modello della tabella dei piatti del ristorante.
        DefaultTableModel modelloMenu = new DefaultTableModel(colonne, 0) {

            // Override del metodo isCellEditable, per impedire che l'utente possa modificare le righe della tabella.
            @Override
            public boolean isCellEditable(int row, int column) {
                // Restituendo false, nessuna cella della tabella sarà modificabile dall'utente.
                return false;
            }
        };

        // Aggiunge al modello di tabella le stringhe dei piatti prelevate precedentemente dal controller.
        for (String[] riga : righe) {
            modelloMenu.addRow(riga);
        }

        // Imposto il modello alla effettiva tabella visualizzata dei piatti del menù.
        tablePiatti.setModel(modelloMenu);

        // Creo il modello della lista dei piatti aggiunti al carrello, quelli visibili nel lato destro della GUI.
        DefaultListModel<String> modelloCarrello = new DefaultListModel<>();

        // Imposto il modello alla effettiva lista visualizzata dei piatti nel carrello.
        carrelloList.setModel(modelloCarrello);

        // Creo una lista per tenere conto di tutti i piatti selezionati dall'utente.
        List<String[]> listaPiatti = new ArrayList<>();

        // Aggiungo una azione al click del pulsante "aggiungiAlCarrelloButton".
        aggiungiAlCarrelloButton.addActionListener(e -> {

            // Ottengo l'indice della riga che l'utente ha selezionato con il mouse.
            int riga = tablePiatti.getSelectedRow();

            // Se l'utente non ha cliccato su nessuna riga:
            if (riga == -1) {
                // Mostra messaggio di errore "Seleziona un piatto".
                JOptionPane.showMessageDialog(frame, "Seleziona un piatto.",
                        "Errore", JOptionPane.ERROR_MESSAGE);
            }
            // Se l'utente ha invece selezionato una riga:
            else {

                // Ottengo l'id del piatto selezionato, che si trova alla colonna 0 della riga selezionata.
                Long idPiatto = Long.parseLong(tablePiatti.getValueAt(riga, 0).toString());
                // Ottengo il nome del piatto selezionato, che si trova alla colonna 1 della riga selezionata.
                String nomePiatto = tablePiatti.getValueAt(riga, 1).toString();
                // Ottengo il prezzo del piatto selezionato, che si trova alla colonna 3 della riga selezionata.
                String prezzoPiatto = tablePiatti.getValueAt(riga, 3).toString();

                // Aggiungo alla lista dei piatti
                listaPiatti.add(new String[]{idPiatto.toString(), nomePiatto, prezzoPiatto});

                // Se l'aggiunta del piatto al carrello va a buon fine:
                if (ControllerEffettuaOrdine.aggiungiPiattoAlCarrello(idRistorante, idPiatto)) {

                    // Aggiungo il nuovo piatto alla vista laterale "Carrello".
                    modelloCarrello.addElement(nomePiatto + " " + prezzoPiatto);

                }
            }
        });

        // Aggiungo una azione al click del pulsante "inviaOrdineButton".
        inviaOrdineButton.addActionListener(e -> {
            boolean carrelloVuoto = ControllerEffettuaOrdine.isCarrelloVuoto();

            if (carrelloVuoto) {

                // Mostro messaggio di errore.
                JOptionPane.showMessageDialog(frame, "Nessun piatto aggiunto al carrello!",
                        "Errore", JOptionPane.ERROR_MESSAGE);
            }
            else {

                // Passo alla schermata di conferma ordine.
                if (frameConfermaOrdine == null || !frameConfermaOrdine.isDisplayable()) {
                    classConfermaOrdine = new FrameConfermaOrdine();
                    frameConfermaOrdine = classConfermaOrdine.apriFrameConfermaOrdine(idRistorante, listaPiatti);
                    frameConfermaOrdine.setLocationRelativeTo(null);
                    frameConfermaOrdine.setVisible(true);
                } else {
                    frameConfermaOrdine.toFront();
                    frameConfermaOrdine.requestFocus();
                }

                // Rendo invisibile questa finestra.
                frame.setVisible(false);

                // Quando la finestra di conferma ordine si chiude:
                frameConfermaOrdine.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent windowEvent) {

                        // Se si è chiusa perché l'ordine è stato confermato:
                        if (classConfermaOrdine.ordineInviato) {
                            // Chiude anche questa finestra di visualizzazione menù.
                            frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
                        }
                        // Altrimenti, se si chiude perché l'utente è uscito:
                        else {
                            // Ritorna visibile questa finestra di visualizzazione menù.
                            frame.setVisible(true);
                        }
                    }
                });
            }
        });

        // Altre proprietà grafiche della finestra.
        try { UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); SwingUtilities.updateComponentTreeUI(frame); } catch (Exception ignored) {}
        aggiungiPiattiPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        tablePiatti.setFillsViewportHeight(true);
        tablePiatti.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablePiatti.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablePiatti.getColumnModel().getColumn(0).setMaxWidth(60);
        tablePiatti.setRowHeight(32);
        carrelloList.setPreferredSize(new Dimension(300, 400));
        for (Component c : aggiungiPiattiPanel.getComponents()) { c.setFont(new Font(c.getFont().getName(), Font.PLAIN, 16)); if (c instanceof JScrollPane) { ((JScrollPane)c).getViewport().getView().setFont(new Font(c.getFont().getName(), Font.PLAIN, 15)); } }
        labelMenu.setFont(new Font(labelMenu.getFont().getName(), Font.BOLD, 20));
        carrelloLabel.setFont(new Font(carrelloLabel.getFont().getName(), Font.BOLD, 20));

        frame.setSize(1100, 700);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        return frame;
    }

}
