package Boundary.EffettuaOrdine;

import Controller.ControllerEffettuaOrdine;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.util.List;

public class FrameConfermaOrdine {

    // Elementi presenti nella finestra.
    private JPanel confermaOrdinePanel;
    private JLabel riepilogoLabel;
    private JList<String> carrelloList;
    private JTextField indirizzoTextField;
    private JButton confermaButton;
    private JScrollPane carrelloScrollPanel;
    private JLabel indirizzoLabel;

    // Variabile per gestire la modalità di chiusura della finestra: se l'ordine è stato inviato o meno.
    boolean ordineInviato = false;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        confermaOrdinePanel = new JPanel();
        confermaOrdinePanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        riepilogoLabel = new JLabel();
        riepilogoLabel.setText("Riepilogo ordine");
        confermaOrdinePanel.add(riepilogoLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indirizzoTextField = new JTextField();
        indirizzoTextField.setText("");
        indirizzoTextField.setToolTipText("Indirizzo di consegna");
        confermaOrdinePanel.add(indirizzoTextField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        confermaButton = new JButton();
        confermaButton.setText("Conferma ordine");
        confermaOrdinePanel.add(confermaButton, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        carrelloScrollPanel = new JScrollPane();
        confermaOrdinePanel.add(carrelloScrollPanel, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 1, false));
        carrelloList = new JList();
        carrelloList.setLayoutOrientation(0);
        carrelloScrollPanel.setViewportView(carrelloList);
        indirizzoLabel = new JLabel();
        indirizzoLabel.setText("Indirizzo di consegna:");
        confermaOrdinePanel.add(indirizzoLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return confermaOrdinePanel;
    }

    // Metodo necessario per aprire la finestra di "Conferma ordine" da altre classi.
    // Restituisce il frame, cioè la finestra di "Conferma ordine".
    public JFrame apriFrameConfermaOrdine(Long idRistorante, List<String[]> listaPiatti) {

        // Creo l'istanza del frame do Conferma Ordine con titolo "Conferma Ordine".
        JFrame frame = new JFrame("Conferma Ordine");

        // Imposta "confermaOrdinePanel" come attuale pannello visibile della finestra.
        frame.setContentPane(confermaOrdinePanel);

        // Specifica che al click della "X" della finestra, non viene chiusa tutta l'applicazione.
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Creo il modello per la lista e lo popolo con i piatti del carrello precedentemente prelevati.
        DefaultListModel<String> modelloCarrello = new DefaultListModel<>();
        carrelloList.setModel(modelloCarrello);
        for (String[] s : listaPiatti) {
            modelloCarrello.addElement(s[1] + " " + s[2] + " €");
        }

        // Aggiungo una azione al click del pulsante "confermaButton".
        confermaButton.addActionListener(e -> {

            // Prelevo l'indirizzo digitato dall'utente.
            String indirizzo = indirizzoTextField.getText();

            // Se l'utente non ha specificato nessun indirizzo:
            if (indirizzo.isEmpty()) {

                // Mostra messaggio di errore.
                JOptionPane.showMessageDialog(frame, "Nessun indirizzo di consegna specificato.",
                        "Errore", JOptionPane.ERROR_MESSAGE);
            }
            // Altrimenti, se l'utente ha specificato un indirizzo:
            else {

                // Se l'invio dell'ordine va a buon fine:
                if (ControllerEffettuaOrdine.inviaOrdine(idRistorante, indirizzo)) {

                    // Mostra messaggio di conferma.
                    JOptionPane.showMessageDialog(frame, "Ordine confermato.",
                            "Successo", JOptionPane.INFORMATION_MESSAGE);

                    // La variabile interna viene aggiornata.
                    ordineInviato = true;

                    // La finestra di conferma ordine viene chiusa.
                    frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));

                }
                // Altrimenti, se l'invio dell'ordine fallisce:
                else {

                    // Mostra messaggio di errore.
                    JOptionPane.showMessageDialog(frame, "Ordine non creato.",
                            "Errore", JOptionPane.ERROR_MESSAGE);

                    // La finestra di conferma ordine viene chiusa.
                    frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
                }

            }

        });

        // Altre proprietà grafiche della finestra.
        try { UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); SwingUtilities.updateComponentTreeUI(frame); } catch (Exception ignored) {}
        confermaOrdinePanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        for (Component c : confermaOrdinePanel.getComponents()) { c.setFont(new Font(c.getFont().getName(), Font.PLAIN, 16)); if (c instanceof JScrollPane) { ((JScrollPane)c).getViewport().getView().setFont(new Font(c.getFont().getName(), Font.PLAIN, 15)); } }
        riepilogoLabel.setFont(new Font(riepilogoLabel.getFont().getName(), Font.BOLD, 20));

        frame.setSize(1100, 700);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        return frame;
    }
}
